# Numerical Python

In [1]:
import numpy as np

In [2]:
array_a = np.array([1,2,3,4]) # numpy array
type(array_a)

numpy.ndarray

In [3]:
array_b = np.array([1,2,3,4],dtype=float)
array_b

array([1., 2., 3., 4.])

In [4]:
np.zeros(10) # sadece 0'lardan oluşan array
np.ones((3,3)) # 3*3 lük 1 lerden oluşan matris
np.empty(10) # çok ufak sayılardan oluşan matris
np.full((3,3),7) # 3*3 lük 7 lerden oluşan matris

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [5]:
np.arange(0,20,3) # start,end,range / 0'dan 20'ye kadar 3 er atlıyarak array oluşturur
np.linspace(0,1,30) # start,end,count / 0 ile 1 arasında 30 adet sayı üreterek array oluşturur

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [6]:
np.random.normal(0,1,(3,4)) # ortalama 0 varyans 1 olacak şekilde 3,4 lük matris oluşturur

array([[-1.73707613,  0.21737594, -0.15716367,  1.97687822],
       [-0.26196291, -1.51657396, -0.39201678,  1.24007802],
       [ 0.76368295, -0.49598451, -0.63942878,  0.29310139]])

In [7]:
np.random.randint(0,10,(2,3)) # 0 ile 10 arasında 2*3 lük matris oluşturur

array([[6, 7, 1],
       [1, 2, 3]])

In [8]:
np.eye(4) # identity matris

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Biçimlendirme
* **ndim** : boyut sayısı
* **shape** : boyut bilgisi
* **size** : toplam eleman sayısı
* **dtype** : array veri tipi

In [9]:
array_b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array_b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
print("Boyut Sayısı",array_b.ndim)
print("Boyut Bilgisi",array_b.shape)
print("Toplam Eleman Sayısı",array_b.size)
print("Veri Tipi",array_b.dtype)

Boyut Sayısı 2
Boyut Bilgisi (2, 5)
Toplam Eleman Sayısı 10
Veri Tipi int64


In [11]:
array_b.reshape(5,2) # reshape arrayi yeniden boyutlandırır

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
np.arange(1,27,3).reshape((3,3))

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [13]:
one_dim_array = np.array([1,2,3])
ndim_array = one_dim_array.reshape((1,3))
ndim_array

array([[1, 2, 3]])

In [14]:
one_dim_array.shape

(3,)

In [15]:
ndim_array.shape

(1, 3)

In [16]:
one_dim_array[np.newaxis,:]

array([[1, 2, 3]])

In [17]:
one_dim_array[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [18]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])

### Birleştirme

In [19]:
np.concatenate([array_1,array_2]) # 2 arrayin birleştirilmesi

array([1, 2, 3, 4, 5, 6])

In [20]:
array_1 = np.array([1,2,3]).reshape((1,3))
array_2 = np.array([4,5,6]).reshape((1,3))

In [21]:
np.concatenate([array_1,array_2]) # 2 boyutlu arraylerin satır bazlı birşeltirilmesi

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.concatenate([array_1,array_2],axis=1) # 2 boyutlu arraylerin sütun bazlı birleştirilmesi

array([[1, 2, 3, 4, 5, 6]])

In [23]:
array_one_dim = np.array([1,2,3])
array_two_dim = np.array([[4,5,6],[7,8,9]])

In [24]:
np.vstack([array_one_dim,array_two_dim]) # 2 matrisi dikey yönlü birleştitme vertical

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
array_1 = np.array([[47],[47]]) # 2 matrisi yatay yönlü birşeltirme horizontal

In [26]:
np.hstack([array_1,array_two_dim])

array([[47,  4,  5,  6],
       [47,  7,  8,  9]])

### Ayırma 

In [27]:
array = np.array([1,2,3,4,5,6,7,8,9])

In [28]:
np.split(array,3) # arrayi 3 parçaya bölüyor

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [29]:
np.split(array,[3,8]) # 0..2,3..8,9.. 

[array([1, 2, 3]), array([4, 5, 6, 7, 8]), array([9])]

In [30]:
np.split(array,[2,3,5]) # başlangıçtan 2 ye kadar, 2 3 arası , 3 5 arası, 5 ten sona kadar

[array([1, 2]), array([3]), array([4, 5]), array([6, 7, 8, 9])]

In [31]:
array = np.arange(16).reshape((4,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
x,y = np.vsplit(array,2)

In [33]:
np.concatenate([y,x],axis=1)

array([[ 8,  9, 10, 11,  0,  1,  2,  3],
       [12, 13, 14, 15,  4,  5,  6,  7]])

In [34]:
x,y = np.hsplit(array,2)

In [35]:
np.concatenate([x,y])

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### Sıralama

In [88]:
array = np.random.randint(0,20,10)
array

array([ 0,  2,  0, 17, 12,  2, 12,  2,  9, 16])

In [89]:
np.sort(array)

array([ 0,  0,  2,  2,  2,  9, 12, 12, 16, 17])

In [90]:
x = np.argsort(array) # liste sıralandıktan sonra değişen index değerleri nelerdir
x

array([0, 2, 1, 5, 7, 8, 4, 6, 9, 3])

### Eleman İşlemleri

In [39]:
array = np.random.randint(50,size=(5,5))
array

array([[37, 33, 26,  3,  1],
       [30, 30, 33, 28, 18],
       [29, 15,  5, 45, 17],
       [40, 24, 13, 46, 16],
       [15, 13, 10, 44, 24]])

In [40]:
array[3,4]

16

In [41]:
array[3,4] = 55

In [42]:
array

array([[37, 33, 26,  3,  1],
       [30, 30, 33, 28, 18],
       [29, 15,  5, 45, 17],
       [40, 24, 13, 46, 55],
       [15, 13, 10, 44, 24]])

In [43]:
array[:,1]

array([33, 30, 15, 24, 13])

In [44]:
array[2:4,1:3]

array([[15,  5],
       [24, 13]])

In [45]:
array[:,0:2]

array([[37, 33],
       [30, 30],
       [29, 15],
       [40, 24],
       [15, 13]])

In [46]:
sup_x = array[0:3,0:3]
sup_x

array([[37, 33, 26],
       [30, 30, 33],
       [29, 15,  5]])

In [47]:
sup_x[0,1] = 9999
sup_x

array([[  37, 9999,   26],
       [  30,   30,   33],
       [  29,   15,    5]])

In [48]:
array # arrayden herhangi bir alt küme alındığında ve o kümede işlem yapıldığında 
      # main kümede o işlemden etlileniyor

array([[  37, 9999,   26,    3,    1],
       [  30,   30,   33,   28,   18],
       [  29,   15,    5,   45,   17],
       [  40,   24,   13,   46,   55],
       [  15,   13,   10,   44,   24]])

In [49]:
sup_y = array[0:3,0:3].copy() # yukardaki problemle karşılaşmamak için copy methodu kullanılır

In [50]:
array = np.random.randint(10,size=10)
array

array([0, 9, 1, 4, 4, 4, 1, 7, 3, 3])

In [51]:
array[[1,3,7]] # 1. 3. 7. indexleri almak için Fancy index yapısı arraye bir liste şeklinde istenilen indexleri
               # vererek oluşturulur

array([9, 4, 7])

In [52]:
array_x = np.random.randint(50,size=(5,5))
array_x

array([[13, 10, 40, 40, 34],
       [27, 13, 42,  8, 28],
       [12, 23,  9,  0, 37],
       [37, 37,  2, 14,  4],
       [25, 18, 27,  7,  3]])

In [53]:
satir = np.array([0,1])
sutun = np.array([1,4])
array_x[satir,sutun]

array([10, 28])

In [54]:
array_x[1,[2,4]] # 1.satırın 2. ve 4. sütünları

array([42, 28])

In [55]:
array_x[[1,3],[2,4]] # 1. satırın 2. sütünu ile 3. satırın 4. sütünu

array([42,  4])

In [56]:
array_x[2:4,[2,3,4]] # 2. ve 3. satırların 2.3.4. sütünları

array([[ 9,  0, 37],
       [ 2, 14,  4]])

### Koşullu Eleman İşlemleri

In [57]:
array = np.arange(10)
array[array > 5] # 5 ten büyük elemanlar True döner

array([6, 7, 8, 9])

In [58]:
array = np.random.randint(20,size=(5,5))
array

array([[ 1, 18,  3,  1, 15],
       [ 5,  4, 11,  2, 14],
       [10, 13,  2, 16, 10],
       [ 9,  8,  8,  7, 11],
       [11,  4, 17,  6, 12]])

In [59]:
np.sum(array>10) # True olan kaç tane değer var 

10

In [60]:
np.sum((array>5) & (array<15))

13

In [61]:
np.sum(array>10,axis=1) # Satır bazında 10 dan büyük kaç tane eleman var

array([2, 2, 2, 1, 3])

In [62]:
np.sum(array>10,axis=0) # Sütun bazında 10 dan büyük kaç tane eleman var

array([1, 2, 2, 1, 4])

In [63]:
np.all(array>10) # Array içerisinde TÜM elemanlar 10 dan büyük mü

False

In [64]:
np.any(array>10) # Array içerisinde EN AZ bir eleman 10 dan büyük mü 

True

In [65]:
np.any(array>10,axis=1) # Satırlarda 10 dan büyük en az bir eleman var mı 

array([ True,  True,  True,  True,  True])

### Arraylerde Matematiksel İşlemler

In [66]:
array_x = np.arange(1,10)
array_x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
array_x ** 2 

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [68]:
array_x / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        , 2.33333333, 2.66666667, 3.        ])

In [69]:
array_x[array_x % 2 == 0]

array([2, 4, 6, 8])

In [70]:
np.add.accumulate(array_x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [71]:
np.mean(array[[2,3],1]) # 2. ve 3 .satırların 1. sütununun ortalaması

10.5

In [72]:
array

array([[ 1, 18,  3,  1, 15],
       [ 5,  4, 11,  2, 14],
       [10, 13,  2, 16, 10],
       [ 9,  8,  8,  7, 11],
       [11,  4, 17,  6, 12]])

In [73]:
array.sum(axis=1)

array([38, 36, 51, 43, 50])

### Broadcasting
* Eğer 2 array boyut sayısı olarak bir birinden farklı ise boyutu az olanın boyutuna 1 ekleyerek boyutu çoğalt
* Eğer eşleşmeyen boyut sayısı varsa 1 olan boyutu diğer array'in boyutuna eşitle 
* Hala Uyuşmazlık varsa hata döndür

In [74]:
array_x = np.arange(1,4)
array_x

array([1, 2, 3])

In [75]:
array_y = np.ones((3,3))
array_y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
array_x + array_y

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [77]:
array_z = array_x.reshape(3,1)
array_z

array([[1],
       [2],
       [3]])

In [78]:
array_x + array_z

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])